services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
  language:
    build: ./docker
    ports:
      - "8080:80"
    volumes: 
      - ./code:/var/www/html

